registry:
  restart: always
  image: registry.cn-wulanchabu.aliyuncs.com/programschool-dev/docker-registry:latest
  ports:
    - 4999:4999
  entrypoint: ./registry
  volumes:
    - /home/ssl:/home/ssl
